/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_simple_ffmpeg(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_simple_ffmpeg(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_simple_ffmpeg(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


 #include "general.h"	


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_die(char * jarg1) {
  char *arg1 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  die(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_video_st_set(void * jarg1, void * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVStream *arg2 = (AVStream *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (AVStream *)jarg2; 
  if (arg1) (arg1)->video_st = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SourceOrDestinatio_video_st_get(void * jarg1) {
  void * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVStream *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (AVStream *) ((arg1)->video_st);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_audio_st_set(void * jarg1, void * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVStream *arg2 = (AVStream *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (AVStream *)jarg2; 
  if (arg1) (arg1)->audio_st = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SourceOrDestinatio_audio_st_get(void * jarg1) {
  void * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVStream *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (AVStream *) ((arg1)->audio_st);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_video_set(void * jarg1, int jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  int arg2 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->video = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SourceOrDestinatio_video_get(void * jarg1) {
  int jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  int result;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (int) ((arg1)->video);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_audio_set(void * jarg1, int jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  int arg2 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->audio = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SourceOrDestinatio_audio_get(void * jarg1) {
  int jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  int result;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (int) ((arg1)->audio);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_url_set(void * jarg1, char * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->url);
    if (arg2) {
      arg1->url = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->url, (const char *)arg2);
    } else {
      arg1->url = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_SourceOrDestinatio_url_get(void * jarg1) {
  char * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  char *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (char *) ((arg1)->url);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_vc_set(void * jarg1, void * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodec *arg2 = (AVCodec *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (AVCodec *)jarg2; 
  if (arg1) (arg1)->vc = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SourceOrDestinatio_vc_get(void * jarg1) {
  void * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodec *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (AVCodec *) ((arg1)->vc);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_ac_set(void * jarg1, void * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodec *arg2 = (AVCodec *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (AVCodec *)jarg2; 
  if (arg1) (arg1)->ac = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SourceOrDestinatio_ac_get(void * jarg1) {
  void * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodec *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (AVCodec *) ((arg1)->ac);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_vctx_set(void * jarg1, void * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodecContext *arg2 = (AVCodecContext *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (AVCodecContext *)jarg2; 
  if (arg1) (arg1)->vctx = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SourceOrDestinatio_vctx_get(void * jarg1) {
  void * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodecContext *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (AVCodecContext *) ((arg1)->vctx);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_actx_set(void * jarg1, void * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodecContext *arg2 = (AVCodecContext *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (AVCodecContext *)jarg2; 
  if (arg1) (arg1)->actx = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SourceOrDestinatio_actx_get(void * jarg1) {
  void * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVCodecContext *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (AVCodecContext *) ((arg1)->actx);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_SourceOrDestinatio_ctx_set(void * jarg1, void * jarg2) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVFormatContext *arg2 = (AVFormatContext *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  arg2 = (AVFormatContext *)jarg2; 
  if (arg1) (arg1)->ctx = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_SourceOrDestinatio_ctx_get(void * jarg1) {
  void * jresult ;
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  AVFormatContext *result = 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  result = (AVFormatContext *) ((arg1)->ctx);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_SourceOrDestinatio() {
  void * jresult ;
  SourceOrDestinatio *result = 0 ;
  
  result = (SourceOrDestinatio *)calloc(1, sizeof(SourceOrDestinatio));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_SourceOrDestinatio(void * jarg1) {
  SourceOrDestinatio *arg1 = (SourceOrDestinatio *) 0 ;
  
  arg1 = (SourceOrDestinatio *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_open_input_source(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  AVFormatContext *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (AVFormatContext *)open_input_source(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_get_video_stream(void * jarg1) {
  int jresult ;
  AVFormatContext *arg1 = (AVFormatContext *) 0 ;
  int result;
  
  arg1 = (AVFormatContext *)jarg1; 
  result = (int)get_video_stream(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_get_audio_stream(void * jarg1) {
  int jresult ;
  AVFormatContext *arg1 = (AVFormatContext *) 0 ;
  int result;
  
  arg1 = (AVFormatContext *)jarg1; 
  result = (int)get_audio_stream(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_alloc_audio_frame(int jarg1, void * jarg2, int jarg3, int jarg4, int jarg5) {
  void * jresult ;
  enum AVSampleFormat arg1 ;
  uint64_t arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  uint64_t *argp2 ;
  AVFrame *result = 0 ;
  
  arg1 = (enum AVSampleFormat)jarg1; 
  argp2 = (uint64_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint64_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  result = (AVFrame *)alloc_audio_frame(arg1,arg2,arg3,arg4,arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_build_audio_swr(void * jarg1, void * jarg2) {
  void * jresult ;
  AVCodecContext *arg1 = (AVCodecContext *) 0 ;
  AVCodecContext *arg2 = (AVCodecContext *) 0 ;
  struct SwrContext *result = 0 ;
  
  arg1 = (AVCodecContext *)jarg1; 
  arg2 = (AVCodecContext *)jarg2; 
  result = (struct SwrContext *)build_audio_swr(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_open_source(char * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  int arg3 ;
  InputSource *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (InputSource *)open_source(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_open_output(char * jarg1, void * jarg2, void * jarg3, void * jarg4, int jarg5, int jarg6) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  AVStream *(*arg2)(AVFormatContext *,AVCodecContext *,char *) = (AVStream *(*)(AVFormatContext *,AVCodecContext *,char *)) 0 ;
  AVStream *(*arg3)(AVFormatContext *,AVCodecContext *,char *) = (AVStream *(*)(AVFormatContext *,AVCodecContext *,char *)) 0 ;
  InputSource *arg4 = (InputSource *) 0 ;
  int arg5 ;
  int arg6 ;
  Output *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (AVStream *(*)(AVFormatContext *,AVCodecContext *,char *))jarg2; 
  arg3 = (AVStream *(*)(AVFormatContext *,AVCodecContext *,char *))jarg3; 
  arg4 = (InputSource *)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  result = (Output *)open_output(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_swr_ctx_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  struct SwrContext *arg2 = (struct SwrContext *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (struct SwrContext *)jarg2; 
  if (arg1) (arg1)->swr_ctx = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_swr_ctx_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  struct SwrContext *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (struct SwrContext *) ((arg1)->swr_ctx);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_sws_ctx_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  struct SwsContext *arg2 = (struct SwsContext *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (struct SwsContext *)jarg2; 
  if (arg1) (arg1)->sws_ctx = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_sws_ctx_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  struct SwsContext *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (struct SwsContext *) ((arg1)->sws_ctx);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_curr_packet_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket arg2 ;
  AVPacket *argp2 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  argp2 = (AVPacket *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null AVPacket", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->curr_packet = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_curr_packet_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket result;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result =  ((arg1)->curr_packet);
  {
    AVPacket * resultptr = (AVPacket *) malloc(sizeof(AVPacket));
    memmove(resultptr, &result, sizeof(AVPacket));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_video_packet_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket arg2 ;
  AVPacket *argp2 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  argp2 = (AVPacket *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null AVPacket", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->video_packet = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_video_packet_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket result;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result =  ((arg1)->video_packet);
  {
    AVPacket * resultptr = (AVPacket *) malloc(sizeof(AVPacket));
    memmove(resultptr, &result, sizeof(AVPacket));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_copy_current_packet_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket arg2 ;
  AVPacket *argp2 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  argp2 = (AVPacket *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null AVPacket", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->copy_current_packet = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_copy_current_packet_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket result;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result =  ((arg1)->copy_current_packet);
  {
    AVPacket * resultptr = (AVPacket *) malloc(sizeof(AVPacket));
    memmove(resultptr, &result, sizeof(AVPacket));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_audio_packet_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket arg2 ;
  AVPacket *argp2 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  argp2 = (AVPacket *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null AVPacket", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->audio_packet = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_audio_packet_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVPacket result;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result =  ((arg1)->audio_packet);
  {
    AVPacket * resultptr = (AVPacket *) malloc(sizeof(AVPacket));
    memmove(resultptr, &result, sizeof(AVPacket));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_ivframe_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *arg2 = (AVFrame *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (AVFrame *)jarg2; 
  if (arg1) (arg1)->ivframe = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_ivframe_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (AVFrame *) ((arg1)->ivframe);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_ovframe_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *arg2 = (AVFrame *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (AVFrame *)jarg2; 
  if (arg1) (arg1)->ovframe = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_ovframe_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (AVFrame *) ((arg1)->ovframe);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_iaframe_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *arg2 = (AVFrame *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (AVFrame *)jarg2; 
  if (arg1) (arg1)->iaframe = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_iaframe_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (AVFrame *) ((arg1)->iaframe);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_oaframe_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *arg2 = (AVFrame *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (AVFrame *)jarg2; 
  if (arg1) (arg1)->oaframe = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_oaframe_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  AVFrame *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (AVFrame *) ((arg1)->oaframe);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_dest_pict_buffer_size_set(void * jarg1, int jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  int arg2 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->dest_pict_buffer_size = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_TranscodingContext_dest_pict_buffer_size_get(void * jarg1) {
  int jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  int result;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (int) ((arg1)->dest_pict_buffer_size);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_dest_pict_buffer_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  if (arg1) (arg1)->dest_pict_buffer = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_dest_pict_buffer_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (uint8_t *) ((arg1)->dest_pict_buffer);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_internal_ptr_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (void *)jarg2; 
  if (arg1) (arg1)->internal_ptr = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_internal_ptr_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  void *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (void *) ((arg1)->internal_ptr);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_before_decode_video_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->before_decode_video = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_before_decode_video_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->before_decode_video);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_after_decode_video_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->after_decode_video = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_after_decode_video_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->after_decode_video);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_after_convert_video_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->after_convert_video = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_after_convert_video_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->after_convert_video);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_before_encode_video_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->before_encode_video = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_before_encode_video_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->before_encode_video);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_after_encode_video_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->after_encode_video = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_after_encode_video_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->after_encode_video);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_before_decode_audio_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->before_decode_audio = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_before_decode_audio_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->before_decode_audio);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_after_decode_audio_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->after_decode_audio = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_after_decode_audio_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->after_decode_audio);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_after_convert_audio_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->after_convert_audio = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_after_convert_audio_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->after_convert_audio);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_before_encode_audio_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->before_encode_audio = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_before_encode_audio_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->before_encode_audio);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_after_encode_audio_set(void * jarg1, void * jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *arg2 = (TranscodingFunc *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (TranscodingFunc *)jarg2; 
  if (arg1) (arg1)->after_encode_audio = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_TranscodingContext_after_encode_audio_get(void * jarg1) {
  void * jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  TranscodingFunc *result = 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (TranscodingFunc *) ((arg1)->after_encode_audio);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_first_vpts_set(void * jarg1, int jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  int arg2 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->first_vpts = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_TranscodingContext_first_vpts_get(void * jarg1) {
  int jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  int result;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (int) ((arg1)->first_vpts);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TranscodingContext_first_apts_set(void * jarg1, int jarg2) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  int arg2 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->first_apts = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_TranscodingContext_first_apts_get(void * jarg1) {
  int jresult ;
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  int result;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  result = (int) ((arg1)->first_apts);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_TranscodingContext() {
  void * jresult ;
  struct TranscodingContext *result = 0 ;
  
  result = (struct TranscodingContext *)calloc(1, sizeof(struct TranscodingContext));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_TranscodingContext(void * jarg1) {
  struct TranscodingContext *arg1 = (struct TranscodingContext *) 0 ;
  
  arg1 = (struct TranscodingContext *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_build_transcoding_context(void * jarg1, void * jarg2) {
  void * jresult ;
  InputSource *arg1 = (InputSource *) 0 ;
  Output *arg2 = (Output *) 0 ;
  TranscodingContext *result = 0 ;
  
  arg1 = (InputSource *)jarg1; 
  arg2 = (Output *)jarg2; 
  result = (TranscodingContext *)build_transcoding_context(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_close_source(void * jarg1) {
  int jresult ;
  InputSource *arg1 = (InputSource *) 0 ;
  int result;
  
  arg1 = (InputSource *)jarg1; 
  result = (int)close_source(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_close_output(void * jarg1) {
  int jresult ;
  Output *arg1 = (Output *) 0 ;
  int result;
  
  arg1 = (Output *)jarg1; 
  result = (int)close_output(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_close_transcoding_context(void * jarg1) {
  int jresult ;
  TranscodingContext *arg1 = (TranscodingContext *) 0 ;
  int result;
  
  arg1 = (TranscodingContext *)jarg1; 
  result = (int)close_transcoding_context(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_sff_register_all() {
  sff_register_all();
}


SWIGEXPORT int SWIGSTDCALL CSharp_sff_network_init() {
  int jresult ;
  int result;
  
  result = (int)sff_network_init();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_sff_dump_format(void * jarg1, char * jarg2) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (char *)jarg2; 
  sff_dump_format(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_sff_write_header(void * jarg1) {
  int jresult ;
  Output *arg1 = (Output *) 0 ;
  int result;
  
  arg1 = (Output *)jarg1; 
  result = (int)sff_write_header(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_sff_write_trailer(void * jarg1) {
  int jresult ;
  Output *arg1 = (Output *) 0 ;
  int result;
  
  arg1 = (Output *)jarg1; 
  result = (int)sff_write_trailer(arg1);
  jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

