/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SourceOrDestinatio : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SourceOrDestinatio(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SourceOrDestinatio obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SourceOrDestinatio() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          simple_ffmpegPINVOKE.delete_SourceOrDestinatio(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_AVStream video_st {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_video_st_set(swigCPtr, SWIGTYPE_p_AVStream.getCPtr(value));
    } 
    get {
      IntPtr cPtr = simple_ffmpegPINVOKE.SourceOrDestinatio_video_st_get(swigCPtr);
      SWIGTYPE_p_AVStream ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AVStream(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_AVStream audio_st {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_audio_st_set(swigCPtr, SWIGTYPE_p_AVStream.getCPtr(value));
    } 
    get {
      IntPtr cPtr = simple_ffmpegPINVOKE.SourceOrDestinatio_audio_st_get(swigCPtr);
      SWIGTYPE_p_AVStream ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AVStream(cPtr, false);
      return ret;
    } 
  }

  public int video {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_video_set(swigCPtr, value);
    } 
    get {
      int ret = simple_ffmpegPINVOKE.SourceOrDestinatio_video_get(swigCPtr);
      return ret;
    } 
  }

  public int audio {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_audio_set(swigCPtr, value);
    } 
    get {
      int ret = simple_ffmpegPINVOKE.SourceOrDestinatio_audio_get(swigCPtr);
      return ret;
    } 
  }

  public string url {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_url_set(swigCPtr, value);
    } 
    get {
      string ret = simple_ffmpegPINVOKE.SourceOrDestinatio_url_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_AVCodec vc {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_vc_set(swigCPtr, SWIGTYPE_p_AVCodec.getCPtr(value));
    } 
    get {
      IntPtr cPtr = simple_ffmpegPINVOKE.SourceOrDestinatio_vc_get(swigCPtr);
      SWIGTYPE_p_AVCodec ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AVCodec(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_AVCodec ac {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_ac_set(swigCPtr, SWIGTYPE_p_AVCodec.getCPtr(value));
    } 
    get {
      IntPtr cPtr = simple_ffmpegPINVOKE.SourceOrDestinatio_ac_get(swigCPtr);
      SWIGTYPE_p_AVCodec ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AVCodec(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_AVCodecContext vctx {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_vctx_set(swigCPtr, SWIGTYPE_p_AVCodecContext.getCPtr(value));
    } 
    get {
      IntPtr cPtr = simple_ffmpegPINVOKE.SourceOrDestinatio_vctx_get(swigCPtr);
      SWIGTYPE_p_AVCodecContext ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AVCodecContext(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_AVCodecContext actx {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_actx_set(swigCPtr, SWIGTYPE_p_AVCodecContext.getCPtr(value));
    } 
    get {
      IntPtr cPtr = simple_ffmpegPINVOKE.SourceOrDestinatio_actx_get(swigCPtr);
      SWIGTYPE_p_AVCodecContext ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AVCodecContext(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_AVFormatContext ctx {
    set {
      simple_ffmpegPINVOKE.SourceOrDestinatio_ctx_set(swigCPtr, SWIGTYPE_p_AVFormatContext.getCPtr(value));
    } 
    get {
      IntPtr cPtr = simple_ffmpegPINVOKE.SourceOrDestinatio_ctx_get(swigCPtr);
      SWIGTYPE_p_AVFormatContext ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AVFormatContext(cPtr, false);
      return ret;
    } 
  }

  public SourceOrDestinatio() : this(simple_ffmpegPINVOKE.new_SourceOrDestinatio(), true) {
  }

}
