# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/work/libav_samples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/work/libav_samples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/work/libav_samples/CMakeFiles /media/work/libav_samples/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/work/libav_samples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named output-example

# Build rule for target.
output-example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output-example
.PHONY : output-example

# fast build rule for target.
output-example/fast:
	$(MAKE) -f CMakeFiles/output-example.dir/build.make CMakeFiles/output-example.dir/build
.PHONY : output-example/fast

#=============================================================================
# Target rules for targets named simple_ffmpeg_player

# Build rule for target.
simple_ffmpeg_player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_ffmpeg_player
.PHONY : simple_ffmpeg_player

# fast build rule for target.
simple_ffmpeg_player/fast:
	$(MAKE) -f CMakeFiles/simple_ffmpeg_player.dir/build.make CMakeFiles/simple_ffmpeg_player.dir/build
.PHONY : simple_ffmpeg_player/fast

output-example.o: output-example.c.o
.PHONY : output-example.o

# target to build an object file
output-example.c.o:
	$(MAKE) -f CMakeFiles/output-example.dir/build.make CMakeFiles/output-example.dir/output-example.c.o
.PHONY : output-example.c.o

output-example.i: output-example.c.i
.PHONY : output-example.i

# target to preprocess a source file
output-example.c.i:
	$(MAKE) -f CMakeFiles/output-example.dir/build.make CMakeFiles/output-example.dir/output-example.c.i
.PHONY : output-example.c.i

output-example.s: output-example.c.s
.PHONY : output-example.s

# target to generate assembly for a file
output-example.c.s:
	$(MAKE) -f CMakeFiles/output-example.dir/build.make CMakeFiles/output-example.dir/output-example.c.s
.PHONY : output-example.c.s

simple_ffmpeg_player.o: simple_ffmpeg_player.c.o
.PHONY : simple_ffmpeg_player.o

# target to build an object file
simple_ffmpeg_player.c.o:
	$(MAKE) -f CMakeFiles/simple_ffmpeg_player.dir/build.make CMakeFiles/simple_ffmpeg_player.dir/simple_ffmpeg_player.c.o
.PHONY : simple_ffmpeg_player.c.o

simple_ffmpeg_player.i: simple_ffmpeg_player.c.i
.PHONY : simple_ffmpeg_player.i

# target to preprocess a source file
simple_ffmpeg_player.c.i:
	$(MAKE) -f CMakeFiles/simple_ffmpeg_player.dir/build.make CMakeFiles/simple_ffmpeg_player.dir/simple_ffmpeg_player.c.i
.PHONY : simple_ffmpeg_player.c.i

simple_ffmpeg_player.s: simple_ffmpeg_player.c.s
.PHONY : simple_ffmpeg_player.s

# target to generate assembly for a file
simple_ffmpeg_player.c.s:
	$(MAKE) -f CMakeFiles/simple_ffmpeg_player.dir/build.make CMakeFiles/simple_ffmpeg_player.dir/simple_ffmpeg_player.c.s
.PHONY : simple_ffmpeg_player.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... output-example"
	@echo "... rebuild_cache"
	@echo "... simple_ffmpeg_player"
	@echo "... output-example.o"
	@echo "... output-example.i"
	@echo "... output-example.s"
	@echo "... simple_ffmpeg_player.o"
	@echo "... simple_ffmpeg_player.i"
	@echo "... simple_ffmpeg_player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

